### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by alexeyfadeev** [BedquiltDB/bedquilt-core#20]
Hello. I tried to install bedquilt-core and got an eroor:
"ImportError: No module named jinja2"
I have installed Jinja 2 (pip install Jinja2). Nothig changes

**Comment by ShaneKilkelly** [comment]
Hi Alexey,

I presume you're following the instructions under the "Installation" section of the readme? And I presume it's the `sudo make install` stage which is failing?

Before we debug this issue, I'd like to point out that there is an alternative way to install bedquilt-core from a pre-built package (sorry it's not so well documented in the readme for this repo): 

http://bedquiltdb.readthedocs.org/en/latest/guide/installation/

I would recommend trying that method of installation if you want to get things running right now.

Anyway, back to the main topic:

Can I ask which version of python you are running? What is the output of `env python` and `which python`?

Thanks!

**Comment by alexeyfadeev** [comment]
apt-show-versions python
python:all not installed
python:i386/unstable 2.7.11-1 uptodate

I have no experience with python. Please give me an advice, what should I install

    mkdir -p .tmp/packages/bedquilt--0.6.0
    mkdir -p .tmp/packages/bedquilt--0.6.0/sql
    cp dist/sql/*.sql .tmp/packages/bedquilt--0.6.0/sql/
    ./bin/template.py src/META.json VERSION=0.6.0 \
    	> .tmp/packages/bedquilt--0.6.0/META.json
    Traceback (most recent call last):
      File "./bin/template.py", line 2, in <module>
        import jinja2
    ImportError: No module named jinja2

**Comment by ShaneKilkelly** [comment]
Hi Alexey.

I would advise you to use the installation instructions here, which shouldn't require python/jinja to get up and running: http://bedquiltdb.readthedocs.org/en/latest/guide/installation/

Sorry the original instructions on this repo were a bit confusing, as they were instructions for how to install the development version of bedquilt. If you're still stuck later, or have any other problems, you can always drop into our chat channel at https://gitter.im/BedquiltDB/bedquilt-core, and if I am online I may be able to help in real-time :)

**Comment by ShaneKilkelly** [comment]
Closing, can re-open if issues continue.
